SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `score` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;
USE `score` ;

-- -----------------------------------------------------
-- Table `score`.``
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `score`.`score_snapshot_grp` (
  `EQUIP_CAT_ID` VARCHAR(10) NOT NULL ,
  `MOD_DTE` DATETIME NOT NULL ,
  `DESCR` VARCHAR(255) NULL,
  `USERID` VARCHAR(64) NOT NULL,
  `PRI_SAVE_SET_IND` CHAR NOT NULL,
  PRIMARY KEY (`EQUIP_CAT_ID` , `MOD_DTE`) )
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `score`.`score_snapshot_grp_sgnl` (
   `EQUIP_CAT_ID` VARCHAR(10) NOT NULL,
   `SET_PT_SGNL_ID` VARCHAR(75) NOT NULL,
   `RB_SGNL_ID` VARCHAR(75) NOT NULL,
   `SYS_ID` VARCHAR(10) NOT NULL,
   `FILTER_ID` VARCHAR(10) NULL,
   `USE_RB_IND` CHAR(1) NOT NULL,
   `MOD_BY_UID` VARCHAR(64) NULL,
   `MOD_DTE` DATETIME NULL,
   `ACTIVE_IND` CHAR NOT NULL,
   `PV_DATA_TYPE` VARCHAR(25) NOT NULL,
   `DESCR` VARCHAR(1000) NULL,
   PRIMARY KEY (`EQUIP_CAT_ID`, `SET_PT_SGNL_ID`, `RB_SGNL_ID` ) )
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `score`.`score_snapshot_sgnl` (
    `EQUIP_CAT_ID` VARCHAR(10) NOT NULL,
    `MOD_DTE` DATETIME NOT NULL,
    `SET_PT_SGNL_ID` VARCHAR(75) NOT NULL,
    `RB_SGNL_ID` VARCHAR(75) NOT NULL,
    `SET_PT_SGNL_VAL` VARCHAR(50) NULL,
    `RB_SGNL_VAL` VARCHAR(50) NULL,
    PRIMARY KEY (`EQUIP_CAT_ID`, `MOD_DTE`,`SET_PT_SGNL_ID`, `RB_SGNL_ID`) )
ENGINE = InnoDB;